### ISSUE TITLE
Error Parsing JS8 Traffic

### ISSUE THREAD

**Issue by luarvique** [jketterl/js8py#1]
Got this exception when looking at JS8 traffic at 40m:
```
Jun 27 23:45:46 orange openwebrx[238920]: 2024-06-27 23:45:46,454 - owrx.js8 - ERROR - error while parsing js8 message
Jun 27 23:45:46 orange openwebrx[238920]: Traceback (most recent call last):
Jun 27 23:45:46 orange openwebrx[238920]:   File "/usr/lib/python3/dist-packages/owrx/js8.py", line 100, in parse
Jun 27 23:45:46 orange openwebrx[238920]:     frame = Js8().parse_message(msg)
Jun 27 23:45:46 orange openwebrx[238920]:   File "/usr/lib/python3/dist-packages/js8py/__init__.py", line 21, in parse_message
Jun 27 23:45:46 orange openwebrx[238920]:     return Js8FrameDirected(parsed_msg)
Jun 27 23:45:46 orange openwebrx[238920]:   File "/usr/lib/python3/dist-packages/js8py/frames.py", line 62, in __init__
Jun 27 23:45:46 orange openwebrx[238920]:     self.cmd = [c for c, v in directed_cmds.items() if v == cmd % 32][0]
Jun 27 23:45:46 orange openwebrx[238920]: IndexError: list index out of range
```

**Comment by jketterl** [comment]
Seems like the message contained something invalid. `directed_cmds` is a lookup table, and from what I can tell it only has one undefined value (v == 14, reserved) for v < 32. May be a false positive, or erroneous decode.

What exactly would you expect in such a case? I don't think this is recoverable, so I'd say an error is justified.

**Comment by luarvique** [comment]
I would expect the decoder to register an error, but not crash with an exception. Maybe provide a partial decode.

**Comment by jketterl** [comment]
An exception is an error. That's the way you know something went wrong. I don't think a partial decode makes a lot of sense either.

**Comment by luarvique** [comment]
Not validating input data explicitly, relying on exceptions instead, is not a very good programming practice. Exception is an emergency, not a validation method.

**Comment by jketterl** [comment]
OK, that is something we can work on. The result would however still be an exception. I can try to rework this so that it has its own set of exceptions.

**Comment by luarvique** [comment]
I would say the result the should be a regular log message indicating error and not an exception. But if you would like to create a separate set of exceptions for parsing errors, then catch them and print log messages, I am not the one to judge.

**Comment by jketterl** [comment]
Since this is a library, I don't think simply writing an error message to the log is a sufficient action, and I'd also say that it's up to the calling application on how to handle the error, hence the suggestion to have a custom set of exceptions for better verbosity.

In the context of OpenWebRX, this is already handled very close to what you describe, so not sure what exactly you'd want to change. I don't intend to go back to C-style APIs where the caller has to check the return code for every function call, if that's what you're suggesting.

**Comment by luarvique** [comment]
To be precise, I would like the software check input for errors when trying to parse it, rather than rely on random Python runtime exceptions, as shown above.

If you want to report found errors with case-specific exceptions, rather than return error codes, that is your design choice I have no opinion on. But don't let the parser go haywire, catching its fall at the ground level.
